services:
    php-cli:
        container_name: ${COMPOSE_PROJECT_NAME}_php
        build:
            context: ./php
        volumes:
            - ../app:/app
        ports:
            - "80:80"
    mariadb:
        image: mariadb:latest
        container_name: ${COMPOSE_PROJECT_NAME}_mariadb
        volumes:
            - db-data:/var/lib/mariadb
            - ./mariadb:/docker-entrypoint-initdb.d
        environment:
            MARIADB_DATABASE: ${DB_NAME}
            MARIADB_USER: ${DB_USER}
            MARIADB_PASSWORD: ${DB_PASS}
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
        ports:
            - '60003:3306'

volumes:
    db-data:
        name: db_data
